"""empty message

Revision ID: 2850f71b6aef
Revises: f62589ee8f08
Create Date: 2018-01-30 21:31:03.880460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2850f71b6aef'
down_revision = 'f62589ee8f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('icon_name', sa.String(length=128), nullable=True))
    op.add_column('questions', sa.Column('short_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'short_name')
    op.drop_column('questions', 'icon_name')
    # ### end Alembic commands ###
