"""empty message

Revision ID: 31faadef264a
Revises: b9df6b8795f0
Create Date: 2018-01-30 19:12:24.808246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31faadef264a'
down_revision = 'b9df6b8795f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('image_link', sa.Text(), nullable=True))
    op.add_column('clubs', sa.Column('recruitment_info', sa.Text(), nullable=True))
    op.add_column('clubs', sa.Column('website', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'clubs', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'website')
    op.drop_column('clubs', 'recruitment_info')
    op.drop_column('clubs', 'image_link')
    op.drop_column('clubs', 'admin_id')
    # ### end Alembic commands ###
