"""empty message

Revision ID: 3c6f67d96eb0
Revises: d53a14f2b9ca
Create Date: 2017-11-09 01:56:00.605213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6f67d96eb0'
down_revision = 'd53a14f2b9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_category_association',
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('club_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_category_id'], ['club_categories.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_category_association')
    op.drop_table('club_categories')
    # ### end Alembic commands ###
