"""empty message

Revision ID: b9df6b8795f0
Revises: 3c6f67d96eb0
Create Date: 2017-11-17 01:03:39.874952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9df6b8795f0'
down_revision = '3c6f67d96eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('clubs', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'is_confirmed')
    op.drop_column('clubs', 'description')
    # ### end Alembic commands ###
