"""empty message

Revision ID: d53a14f2b9ca
Revises: d277f2c7a853
Create Date: 2017-11-09 01:16:58.934253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53a14f2b9ca'
down_revision = 'd277f2c7a853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'name')
    # ### end Alembic commands ###
