"""empty message

Revision ID: f62589ee8f08
Revises: 60f555040864
Create Date: 2018-01-30 20:36:13.472489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62589ee8f08'
down_revision = '60f555040864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(length=128), nullable=True))
    op.drop_column('questions', 'max_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('max_rating', sa.INTEGER(), nullable=True))
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'description')
    # ### end Alembic commands ###
